### ISSUE TITLE
HTML parsing

### ISSUE THREAD

**Issue by agentcooper** [Lapple/htmltemplate-parser#1]
1.

``` html
<TMPL_IF something><div class="wrapper"></TMPL_IF>

<div><!-- ... --></div>

<TMPL_IF something></div></TMPL_IF>
```

2.

``` html
<div <TMPL_IF active>class="item--<TMPL_VAR active>"</TMPL_IF>><!-- ... --></div>
```

3.

``` html
<div class="item <TMPL_IF active>item--active</TMPL_IF>"><!-- ... --></div>
```

4.

``` html
<div <TMPL_VAR [% $attributes %]>><!-- ... --></div>
```

**Comment by Lapple** [comment]
- [x] 1
- [x] 2
- [x] 3
- [ ] 4 - wontfix for now, because it'd be pretty hard to generate predictable output

**Comment by Lapple** [comment]
First three cases are somewhat covered, feel free to open new issues if you find something is missing. See [test/html_tags/ast.json](../blob/master/test/html_tags/ast.json) for reference.
