### ISSUE TITLE
Perl expressions

### ISSUE THREAD

**Issue by agentcooper** [Lapple/htmltemplate-parser#4]
We need to parse perl expressions into Esprima tree to convert expressions.

https://github.com/agentcooper/htmltemplate-lint/blob/master/lib/perl-expression-parser/perl-expression.pegjs

``` perl
$a->{prop} eq '3' && $b
```

into

``` js
a.prop === '3' && b
```

**Comment by Lapple** [comment]
Released in 0.3.0
