### ISSUE TITLE
Wrong error message when wrong pair of condition wrap attribute

### ISSUE THREAD

**Issue by pofigizm** [Lapple/htmltemplate-parser#5]
```
<div
    <TMPL_UNLESS noid>
        id="12345"
    </TMPL_IF> 
> 
</div>
```

Throwed error message `"Expected a closing bracket."`
instead `"Expected a </TMPL_UNLESS> but </TMPL_IF> found."`

**Comment by Lapple** [comment]
Missed that, thanks. Will be released later as part of `0.3.0`.
